name: Dr.Kanakadurga Murali
favicon: null
layout_spectrum: 0.8708726707845926
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d1b9a1'
    - '#f7c220'
    - '#9c856e'
    - '#262019'
    - '#ffffff'
  brandStrength: 0.6410679097753018
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.8170143228489906
purpose: []
