name: Dr.Kanakadurga Murali
favicon: null
layout_spectrum: 0.8708726707845926
typography_spectrum: 0.0267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ed1c24'
    - '#f05b47'
    - '#bff073'
    - '#0dc9f7'
    - '#7f7f7f'
  brandStrength: 0.9375
  lightness: 0.125
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
