name: Dr.Kanakadurga Murali
favicon: null
layout_spectrum: 0.8708726707845926
typography_spectrum: 0.8817781794350594
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6410679097753018
  lightness: 0.6896987126674503
  saturation: 0.41807418782263994
  rhythmicContrast: 0.8170143228489906
purpose: []
