name: Dr.Kanakadurga Murali
favicon: null
layout_spectrum: 0.8708726707845926
typography_spectrum: 0.28486
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2671f'
    - '#c91b26'
    - '#160a47'
    - '#60047a'
    - '#9c0f5f'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
