name: Dr.Kanakadurga Murali
favicon: null
layout_spectrum: 0.8708726707845926
typography_spectrum: 0.0267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fe9601'
    - '#cc0063'
    - '#00b796'
    - '#00d2f1'
    - '#86269b'
  brandStrength: 0.9375
  lightness: 0.125
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
