name: Dr.Kanakadurga Murali
favicon: null
layout_spectrum: 0.8708726707845926
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdf200'
    - '#542733'
    - '#e94c6f'
    - '#c6d5cd'
    - '#5a6a62'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 1
purpose: []
